#!/bin/sh
set -e
# This is a Bourne shell script that calls AppleScript.
# It's a pain to resolve file names in AppleScript,
# so we do it in Bourne first.

beforeFile="$(realpath "$1")"
afterFile="$(realpath "$2")"
comparisonFileArg="$3"
authorName="$4"
if test -z "$beforeFile" || test -z "$afterFile" || test -z "$comparisonFileArg"; then
  echo "Usage: <before.docx> <after.docx> <output.docx> [author name]"
  exit 1
fi

comparisonFileDirectory=$(realpath "$(dirname "$comparisonFileArg")")
comparisonFile="$comparisonFileDirectory/$(basename "$comparisonFileArg")"

osascript <<SCRIPT
on run
  tell application "Microsoft Word"
    open (POSIX file "$beforeFile")
    set beforeDocument to active document
    if "$authorName" = "" then
      compare beforeDocument path (POSIX file "$afterFile")
    else
      compare beforeDocument path (POSIX file "$afterFile") author name "$authorName"
    end if
    set comparisonDocument to active document
    save as comparisonDocument file name (POSIX file "$comparisonFile") file format format document
    close comparisonDocument saving no
    close beforeDocument saving no
  end tell
end run
SCRIPT

echo "Wrote $comparisonFile."
